### ISSUE TITLE
Big-endian vs Little-endian

### ISSUE THREAD

**Issue by liyishuai** [liyishuai/coq-http2#4]
The network bytes are big-endian, whereas little-endian makes numeric conversion simpler and more reason-able. We should probably represent the fields in little-endian vectors, and only use big-endian when transforming them into strings.

**Comment by olekgierczak** [comment]
To add, coq BVectors are little endian (in case we want to use any of the built in functions) and ascii's constructor is also little endian.

**Comment by lastland** [comment]
Maybe you want to check MIT's bit vector library (https://github.com/mit-plv/bbv).

**Comment by liyishuai** [comment]
Are there potential difficulties with Coq's `Vector` addressed by `bbv`?

**Comment by lastland** [comment]
I only know the existence of such a library. Whenever you find some problems with Coq's `Vector`, check it out!
