### ISSUE TITLE
Meaning of zeroFrameType

### ISSUE THREAD

**Issue by Lysxia** [liyishuai/coq-http2#6]
What is the meaning of `zeroFrameType` and `nonZeroFramType` and why is `WindowUpdateType` in neither?

**Comment by liyishuai** [comment]
They're used in `Decode.checkFrameHeader`:
- `zeroFrameType` decides whether a frame can only be used in control streams (those with ID 0)
- `nonZeroFrameType` decides whether a frame cannot be used in control stream

The namings are copied from Haskell [HTTP2](https://hackage.haskell.org/package/http2-1.6.3/docs/src/Network-HTTP2-Decode.html#checkFrameHeader) package. We could pick better names for them.
